[package]
name = "scx_raw_pmu"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.65"
csv = "1.3.1"
procfs = "0.18"
regex = "1.11.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
scx_utils = { path = "../scx_utils", version = "1.0.19" }

[build-dependencies]
scx_utils = { path = "../scx_utils", version = "1.0.19" }
